### ISSUE TITLE
Add docker-compose file

### ISSUE THREAD

**Issue by JBlond** [artem-panchenko/counter-strike-docker#15]
```yaml
name: cs-docker
services:
    hlds:
        ports:
            - 27020:27015/udp
        environment:
            - START_MAP=de_inferno
            - ADMIN_STEAM=0:1:1234566
            - SERVER_NAME=My Server
        container_name: cs
        image: hlds:alpha
```
